### ISSUE TITLE
[BUG] Does not execute if run from tagged version

### ISSUE THREAD

**Issue by pdf** [TheWisker/aur-update#1]
### Explanation

When attempting to use this action at the v1 tag it errors with:

```
Run /__w/_actions/TheWisker/aur-update/master/scripts/setup.sh
  /__w/_actions/TheWisker/aur-update/master/scripts/setup.sh
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    aur_key: ***
/__w/_temp/62570cbd-8df6-490a-a2c0-679da9ebf3bc.sh: line 1: /__w/_actions/TheWisker/aur-update/master/scripts/setup.sh: No such file or directory
Error: Process completed with exit code 127.
```

It's important that versioned actions work so that users know what code they're running, and so that runs are consistent - operating from master is a very bad idea, but the action hardcodes the magic checkout path, including the master branch ref.

### Action to reproduce

```yaml
name: AUR

on:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: "aur"
  cancel-in-progress: true

jobs:
  aur:
    environment:
      name: aur-update
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: AUR update
        uses: TheWisker/aur-update@v1
        with:
          aur_key: ${{ secrets.AUR_KEY }}
          email: ${{ secrets.AUR_EMAIL }}
```

### Action Version

v1

### Additional Context

It would probably make sense to use the `uses: docker` action with a Dockerfile instead of `uses: composite` for a couple of reasons:

- All files can be placed in the container at a predictable location that's not tied to the checkout path.
- The Dockerfile could use `FROM archlinux:base` instead of requiring users to override the `container` in their actions.

### Relevant log output

```shell
Run TheWisker/aur-update@v1
  with:
    aur_key: ***
    email: ***
    ref: master
    username: pdf
    repo: pdf/hyprpanel
    repo_name: hyprpanel
    aur_folder: ./aur
    tag_name: v0.1.5
Run /__w/_actions/TheWisker/aur-update/master/scripts/setup.sh
  /__w/_actions/TheWisker/aur-update/master/scripts/setup.sh
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    aur_key: ***
/__w/_temp/62570cbd-8df6-490a-a2c0-679da9ebf3bc.sh: line 1: /__w/_actions/TheWisker/aur-update/master/scripts/setup.sh: No such file or directory
Error: Process completed with exit code 127.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
